name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      custom_command:
        description: 'custom command'
        default: ''
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dex2xml
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymysql
    - name: Checkout dexonline-docker
      uses: actions/checkout@v4
      with:
        repository: david-batranu/dexonline-docker
        path: 'dexonline-docker'
    - name: Build the Docker image
      run: docker build . --file ./dexonline-docker/Dockerfile --tag dexonline-docker:$(date +%s)
    - name: Run custom command
      run: ${{ inputs.custom_command }}
