name: Deploy

on:
  workflow_dispatch:
    inputs:
      default_dict:
        description: 'Generate the default dictionary'
        default: true
        required: false
        type: boolean
      custom_dict:
        description: 'Generate a dictionary with custom sources'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dex2xml
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Setup and install dependencies
      run: |
        mkdir db
        sudo tar -xvzf kindlegen_linux_2.6_i386_v2_9.tar.gz -C /usr/bin/ kindlegen
        python -m pip install --upgrade pip
        pip install pymysql
    - name: Cache database
      uses: actions/cache@v4
      id: db-cache
      with:
        path: ./db/dex-database.sql.gz
        key: dex-database
        restore-keys: dex-database
    - name: Download database
      if: steps.db-cache.outputs.cache-hit != 'true'
      run: wget -O ./db/dex-database.sql.gz https://dexonline.ro/static/download/dex-database.sql.gz -nv
    - name: Setup database
      run: |
        sudo systemctl start mysql.service
        mysql -e 'create database dexonline charset utf8mb4 collate utf8mb4_romanian_ci' -uroot -proot
        zcat ./db/dex-database.sql.gz | mysql -uroot -proot dexonline
    - name: Print database stats
      run: |
        mysql -e "use dexonline; select id, shortName, concat(name, ', ', year) as source, (select count(lexicon) from Definition d where d.status = 0 and d.sourceId = s.id) as defcount, canDistribute from Source s order by id;" -uroot -proot
    - name: Generate the default dictionary
      if: ${{ inputs.default_dict == true }}
      run: |
        python dex2xml.py -p root -s 27 40 65 -o "DEXonline 2025.05"
    - name: Generate the custom dictionary
      if: ${{ inputs.custom_dict != '' }}
      run: |
        python dex2xml.py -p root -s ${{ inputs.custom_dict }} -o "DEXonline custom"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dictionaries-${{ github.sha }}-${{ github.run_number }}
        path: |
          *.*
          !db/*
